// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtarYI_SJfzsfbEAFZbZuOBohcyZpWq8Q',
    appId: '1:1011951789448:web:338f8d477732cb86f9463d',
    messagingSenderId: '1011951789448',
    projectId: 'imagegenrator-880aa',
    authDomain: 'imagegenrator-880aa.firebaseapp.com',
    storageBucket: 'imagegenrator-880aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcWOPrFgjs6_vZt5uS6zN9qZ7YLvr92Aw',
    appId: '1:1020611073979:android:c45f30a5f9f07dcfa7d69e',
    messagingSenderId: '1020611073979',
    projectId: 'musicxy-techinoid',
    storageBucket: 'musicxy-techinoid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB05oBq2ahptL4aJ6-6uSOCtxiMdrid_A',
    appId: '1:1011951789448:ios:adffd3a3c70367bef9463d',
    messagingSenderId: '1011951789448',
    projectId: 'imagegenrator-880aa',
    storageBucket: 'imagegenrator-880aa.firebasestorage.app',
    iosBundleId: 'com.example.imageGenration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB05oBq2ahptL4aJ6-6uSOCtxiMdrid_A',
    appId: '1:1011951789448:ios:adffd3a3c70367bef9463d',
    messagingSenderId: '1011951789448',
    projectId: 'imagegenrator-880aa',
    storageBucket: 'imagegenrator-880aa.firebasestorage.app',
    iosBundleId: 'com.example.imageGenration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtarYI_SJfzsfbEAFZbZuOBohcyZpWq8Q',
    appId: '1:1011951789448:web:1058ee9299c4dccef9463d',
    messagingSenderId: '1011951789448',
    projectId: 'imagegenrator-880aa',
    authDomain: 'imagegenrator-880aa.firebaseapp.com',
    storageBucket: 'imagegenrator-880aa.firebasestorage.app',
  );
}